name: Tests
on:
  push: {}
  workflow_dispatch: {}
env:
  UV_PYTHON_PREFERENCE: only-system
  PKCS11_TOKEN_LABEL: TEST
  PKCS11_TOKEN_PIN: 1234
  PKCS11_TOKEN_SO_PIN: 5678
  SOFTHSM2_CONF: softhsm2.conf
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [ubuntu-latest, windows-latest]
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Acquire sources
        uses: actions/checkout@v4.1.1

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Softhsm
        shell: bash
        run: |
          if [[ $OS_NAME == 'ubuntu-latest' ]]; then
            sudo apt-get install softhsm2
            echo "PKCS11_MODULE=/usr/lib/softhsm/libsofthsm2.so" >> "$GITHUB_ENV"
          else
            choco install softhsm.install
            echo "PKCS11_MODULE=C:\\SoftHSM2\\softhsm2.dll" >> "$GITHUB_ENV"
            echo "C:\\SoftHSM2\\bin" >> "$GITHUB_PATH"
          fi
        env:
          OS_NAME: ${{ matrix.os }}

      - name: Initialize token
        shell: bash
        run: |
          mkdir softhsm_tokens
          echo "directories.tokendir = $(pwd)/softhsm_tokens" > $SOFTHSM2_CONF
          # temporary hack
          if [[ $OS_NAME == 'windows-latest' ]]; then
            U="C:/SoftHSM2/bin/softhsm2-util.exe"
          else
            U=softhsm2-util
          fi
          $U --init-token --free --label $PKCS11_TOKEN_LABEL --pin $PKCS11_TOKEN_PIN --so-pin $PKCS11_TOKEN_SO_PIN
        env:
          OS_NAME: ${{ matrix.os }}
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Install dev dependencies
        run: uv sync --all-extras
      - name: Run tests
        run: uv run pytest -v